// This file was generated by gir (7484d29) from gir-files (71d73f0)
// DO NOT EDIT

use ffi;
use gdk;
use glib;
use glib::Value;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::boxed::Box as Box_;
use std::mem;
use std::mem::transmute;
use std::ptr;

glib_wrapper! {
    pub struct ColorChooserRequest(Object<ffi::WebKitColorChooserRequest>);

    match fn {
        get_type => || ffi::webkit_color_chooser_request_get_type(),
    }
}

pub trait ColorChooserRequestExt {
    #[cfg(feature = "v2_8")]
    fn cancel(&self);

    #[cfg(feature = "v2_8")]
    fn finish(&self);

    #[cfg(feature = "v2_8")]
    fn get_element_rectangle(&self) -> gdk::Rectangle;

    #[cfg(feature = "v2_8")]
    fn get_rgba(&self) -> gdk::RGBA;

    #[cfg(feature = "v2_8")]
    fn set_rgba(&self, rgba: &gdk::RGBA);

    fn get_property_rgba(&self) -> Option<gdk::RGBA>;

    fn set_property_rgba(&self, rgba: Option<&gdk::RGBA>);

    #[cfg(feature = "v2_8")]
    fn connect_finished<F: Fn(&Self) + 'static>(&self, f: F) -> u64;

    fn connect_property_rgba_notify<F: Fn(&Self) + 'static>(&self, f: F) -> u64;
}

impl<O: IsA<ColorChooserRequest> + IsA<glib::object::Object>> ColorChooserRequestExt for O {
    #[cfg(feature = "v2_8")]
    fn cancel(&self) {
        unsafe {
            ffi::webkit_color_chooser_request_cancel(self.to_glib_none().0);
        }
    }

    #[cfg(feature = "v2_8")]
    fn finish(&self) {
        unsafe {
            ffi::webkit_color_chooser_request_finish(self.to_glib_none().0);
        }
    }

    #[cfg(feature = "v2_8")]
    fn get_element_rectangle(&self) -> gdk::Rectangle {
        unsafe {
            let mut rect = gdk::Rectangle::uninitialized();
            ffi::webkit_color_chooser_request_get_element_rectangle(self.to_glib_none().0, rect.to_glib_none_mut().0);
            rect
        }
    }

    #[cfg(feature = "v2_8")]
    fn get_rgba(&self) -> gdk::RGBA {
        unsafe {
            let mut rgba = gdk::RGBA::uninitialized();
            ffi::webkit_color_chooser_request_get_rgba(self.to_glib_none().0, rgba.to_glib_none_mut().0);
            rgba
        }
    }

    #[cfg(feature = "v2_8")]
    fn set_rgba(&self, rgba: &gdk::RGBA) {
        unsafe {
            ffi::webkit_color_chooser_request_set_rgba(self.to_glib_none().0, rgba.to_glib_none().0);
        }
    }

    fn get_property_rgba(&self) -> Option<gdk::RGBA> {
        let mut value = Value::from(None::<&gdk::RGBA>);
        unsafe {
            gobject_ffi::g_object_get_property(self.to_glib_none().0, "rgba".to_glib_none().0, value.to_glib_none_mut().0);
        }
        value.get()
    }

    fn set_property_rgba(&self, rgba: Option<&gdk::RGBA>) {
        unsafe {
            gobject_ffi::g_object_set_property(self.to_glib_none().0, "rgba".to_glib_none().0, Value::from(rgba).to_glib_none().0);
        }
    }

    #[cfg(feature = "v2_8")]
    fn connect_finished<F: Fn(&Self) + 'static>(&self, f: F) -> u64 {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "finished",
                transmute(finished_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }

    fn connect_property_rgba_notify<F: Fn(&Self) + 'static>(&self, f: F) -> u64 {
        unsafe {
            let f: Box_<Box_<Fn(&Self) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "notify::rgba",
                transmute(notify_rgba_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}

#[cfg(feature = "v2_8")]
unsafe extern "C" fn finished_trampoline<P>(this: *mut ffi::WebKitColorChooserRequest, f: glib_ffi::gpointer)
where P: IsA<ColorChooserRequest> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&ColorChooserRequest::from_glib_borrow(this).downcast_unchecked())
}

unsafe extern "C" fn notify_rgba_trampoline<P>(this: *mut ffi::WebKitColorChooserRequest, _param_spec: glib_ffi::gpointer, f: glib_ffi::gpointer)
where P: IsA<ColorChooserRequest> {
    callback_guard!();
    let f: &&(Fn(&P) + 'static) = transmute(f);
    f(&ColorChooserRequest::from_glib_borrow(this).downcast_unchecked())
}
