// This file was generated by gir (32b0f11) from gir-files (857b8f5)
// DO NOT EDIT

use PermissionRequest;
use ffi;
use glib::translate::*;

glib_wrapper! {
    pub struct GeolocationPermissionRequest(Object<ffi::WebKitGeolocationPermissionRequest>): PermissionRequest;

    match fn {
        get_type => || ffi::webkit_geolocation_permission_request_get_type(),
    }
}

impl GeolocationPermissionRequest {}
