// This file was generated by gir (0f7cd61) from gir-files (0bcaef9)
// DO NOT EDIT

use PermissionRequest;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct InstallMissingMediaPluginsPermissionRequest(Object<ffi::WebKitInstallMissingMediaPluginsPermissionRequest>): PermissionRequest;

    match fn {
        get_type => || ffi::webkit_install_missing_media_plugins_permission_request_get_type(),
    }
}

pub trait InstallMissingMediaPluginsPermissionRequestExt {
    #[cfg(feature = "v2_10")]
    fn get_description(&self) -> Option<String>;
}

impl<O: IsA<InstallMissingMediaPluginsPermissionRequest>> InstallMissingMediaPluginsPermissionRequestExt for O {
    #[cfg(feature = "v2_10")]
    fn get_description(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::webkit_install_missing_media_plugins_permission_request_get_description(self.to_glib_none().0))
        }
    }
}
