// This file was generated by gir (f00d658) from gir-files (1069259)
// DO NOT EDIT

use PermissionRequest;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct NotificationPermissionRequest(Object<ffi::WebKitNotificationPermissionRequest>): PermissionRequest;

    match fn {
        get_type => || ffi::webkit_notification_permission_request_get_type(),
    }
}

impl NotificationPermissionRequest {}
