// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(any(feature = "v2_18", feature = "dox"))]
use glib::object::Cast;
use glib::object::IsA;
#[cfg(any(feature = "v2_18", feature = "dox"))]
use glib::signal::connect_raw;
#[cfg(any(feature = "v2_18", feature = "dox"))]
use glib::signal::SignalHandlerId;
use glib::translate::*;
#[cfg(any(feature = "v2_18", feature = "dox"))]
use glib_sys;
#[cfg(any(feature = "v2_18", feature = "dox"))]
use std::boxed::Box as Box_;
use std::fmt;
#[cfg(any(feature = "v2_18", feature = "dox"))]
use std::mem::transmute;
use webkit2_sys;
#[cfg(any(feature = "v2_18", feature = "dox"))]
use OptionMenuItem;

glib_wrapper! {
    pub struct OptionMenu(Object<webkit2_sys::WebKitOptionMenu, webkit2_sys::WebKitOptionMenuClass, OptionMenuClass>);

    match fn {
        get_type => || webkit2_sys::webkit_option_menu_get_type(),
    }
}

pub const NONE_OPTION_MENU: Option<&OptionMenu> = None;

pub trait OptionMenuExt: 'static {
    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn activate_item(&self, index: u32);

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn close(&self);

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn get_item(&self, index: u32) -> Option<OptionMenuItem>;

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn get_n_items(&self) -> u32;

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn select_item(&self, index: u32);

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn connect_close<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<OptionMenu>> OptionMenuExt for O {
    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn activate_item(&self, index: u32) {
        unsafe {
            webkit2_sys::webkit_option_menu_activate_item(self.as_ref().to_glib_none().0, index);
        }
    }

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn close(&self) {
        unsafe {
            webkit2_sys::webkit_option_menu_close(self.as_ref().to_glib_none().0);
        }
    }

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn get_item(&self, index: u32) -> Option<OptionMenuItem> {
        unsafe {
            from_glib_none(webkit2_sys::webkit_option_menu_get_item(
                self.as_ref().to_glib_none().0,
                index,
            ))
        }
    }

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn get_n_items(&self) -> u32 {
        unsafe { webkit2_sys::webkit_option_menu_get_n_items(self.as_ref().to_glib_none().0) }
    }

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn select_item(&self, index: u32) {
        unsafe {
            webkit2_sys::webkit_option_menu_select_item(self.as_ref().to_glib_none().0, index);
        }
    }

    #[cfg(any(feature = "v2_18", feature = "dox"))]
    fn connect_close<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn close_trampoline<P, F: Fn(&P) + 'static>(
            this: *mut webkit2_sys::WebKitOptionMenu,
            f: glib_sys::gpointer,
        ) where
            P: IsA<OptionMenu>,
        {
            let f: &F = &*(f as *const F);
            f(&OptionMenu::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"close\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    close_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for OptionMenu {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "OptionMenu")
    }
}
