// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/tauri-apps/gir-files)
// DO NOT EDIT

use crate::PermissionRequest;

glib::wrapper! {
    #[doc(alias = "WebKitPointerLockPermissionRequest")]
    pub struct PointerLockPermissionRequest(Object<ffi::WebKitPointerLockPermissionRequest, ffi::WebKitPointerLockPermissionRequestClass>) @implements PermissionRequest;

    match fn {
        type_ => || ffi::webkit_pointer_lock_permission_request_get_type(),
    }
}

impl PointerLockPermissionRequest {
  pub const NONE: Option<&'static PointerLockPermissionRequest> = None;
}
