// This file was generated by gir (78b1141) from gir-files (???)
// DO NOT EDIT

#[cfg(feature = "v2_6")]
use UserContentInjectedFrames;
#[cfg(feature = "v2_6")]
use UserScriptInjectionTime;
use ffi;
use glib::translate::*;

glib_wrapper! {
    pub struct UserScript(Shared<ffi::WebKitUserScript>);

    match fn {
        ref => |ptr| ffi::webkit_user_script_ref(ptr),
        unref => |ptr| ffi::webkit_user_script_unref(ptr),
    }
}

impl UserScript {

    #[cfg(feature = "v2_6")]
    pub fn new(source: &str, injected_frames: UserContentInjectedFrames, injection_time: UserScriptInjectionTime, whitelist: &[&str], blacklist: &[&str]) -> UserScript {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::webkit_user_script_new(source.to_glib_none().0, injected_frames.to_glib(), injection_time.to_glib(), whitelist.to_glib_none().0, blacklist.to_glib_none().0))
        }
    }
}
