// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use gtk;
use std::fmt;
use webkit2_sys;

glib_wrapper! {
    pub struct WebViewBase(Object<webkit2_sys::WebKitWebViewBase, webkit2_sys::WebKitWebViewBaseClass, WebViewBaseClass>) @extends gtk::Container, gtk::Widget;

    match fn {
        get_type => || webkit2_sys::webkit_web_view_base_get_type(),
    }
}

impl WebViewBase {}

pub const NONE_WEB_VIEW_BASE: Option<&WebViewBase> = None;

impl fmt::Display for WebViewBase {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "WebViewBase")
    }
}
