name: test

on:
  push:
    branches:
      - crate
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        platform:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
        features:
          - { args: --no-default-features, key: no-default }
          - { args: --all-features, key: all }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v7

      - name: install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.platform.target }}

      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1-dev

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ matrix.features.key == 'all' }}

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo build
        run: cargo build --target ${{ matrix.platform.target }} ${{ matrix.features.args }}

      - name: cargo test
        run: cargo test --verbose --target ${{ matrix.platform.target }} ${{ matrix.features.args }}
