on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.51.0"
    steps:
      - run: sudo apt-get install libwebkit2gtk-4.0-dev -y
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        name: "Test"
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: "Build"
        with:
          command: build
          args: --features=v2_30

  fmt:
    name: Regen Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - run: make regen_check

  checker:
    name: gtk-rs checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: gtk-rs/checker
          ref: master
          path: checker
      - working-directory: checker
        run: cargo build --release
      - run: "./checker/target/release/checker ."
      - run: "./checker/check_init_asserts"
